steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  - uses: actions/checkout@v2

  # Runs a single command using the runners shell
  - name: Run a one-line script
    run: echo Hello, world!
    shell: bash

  # Runs a set of commands using the runners shell
  - name: Run a multi-line script
    run: |
      echo Add other actions to build,
      echo test, and deploy your project.
    shell: bash
